[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "georgian-anki-generator"
version = "0.1.0"
description = "A command-line tool to automate the creation of Anki flashcards for learning the Georgian alphabet."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytesseract>=0.3.13",
    "Pillow>=12.1.0",
    "genanki>=0.13.1",
]

[tool.setuptools.packages.find]
where = ["src"]
